Добавил main. Надо пофиксить фото, добавить скрипты
Grads521/myWebSiteVue pull request #6
Opened 2021-04-29 14:03 UTC by Grads521

2021-05-07 12:19 UTC, ninedev-i requested changes

2021-05-09 12:27 UTC, ninedev-i requested changes

2021-05-09 12:27 UTC, ninedev-i commented on src/components/main.vue
> +            document.querySelector('.fio').textContent = 'Исаев Максим Сергеевич';
Никаких qyerySelector быть не должно

2021-05-09 12:27 UTC, ninedev-i commented on src/components/main.vue
> +            buttonPhone.addEventListener('click', togglePhone);
На события в vue мы подписывается иначе

2021-05-13 20:05 UTC, ninedev-i requested changes

2021-05-13 20:05 UTC, ninedev-i commented on src/components/main.vue
> +                show: true,
Что именно show?

2021-05-13 20:05 UTC, ninedev-i commented on src/components/main.vue
> +            <button v-on:click="show = !show">
Перенеси это в methods

2021-05-16 14:39 UTC, ninedev-i requested changes
Почти хорошо

2021-05-16 14:39 UTC, ninedev-i commented on src/components/main.vue
> +                <p v-if="number">89211834241</p>
Плохой нейминг.  Переменная с названием номер содержит значение true?

2021-05-17 06:18 UTC, ninedev-i requested changes

2021-05-17 06:18 UTC, ninedev-i commented on src/components/main.vue
> +                <p v-if="isPhoneInvisible">89211834241</p>
Примет плохой нейминг.
У тебя написано:
Показать телефон, еслиТелефонНевидимый.
Мне кажется должно быть наоборот

2021-05-17 08:37 UTC, Grads521 commented on src/components/main.vue
> +                <p v-if="isPhoneInvisible">89211834241</p>
Да. Должно быть видим ли мы телефон. А не, невидим ли он

2021-05-17 08:58 UTC, ninedev-i requested changes
#

2021-05-17 08:58 UTC, ninedev-i commented on src/components/main.vue
> +                isPhoneVisible: true,
Я думал по умолчанию он должен быть невидимый, разве нет?

2021-05-17 08:58 UTC, ninedev-i commented on src/components/main.vue
> +            showNumber: function () {
Метод не только показывает номер, но и скрывает его. Лучше назвать toggleNumberVisibility

2021-05-17 10:35 UTC, Grads521 commented on src/components/main.vue
> +                isPhoneVisible: true,
У нас кнопка с надписью 'скрыть телефон',  поэтому телефон виден. Я просто тогда поменяю надпись и скрою

2021-05-17 10:35 UTC, Grads521 commented on src/components/main.vue
> +            showNumber: function () {
Ну я не знал как назвать этот метод, который показывает и скрывает. Твой вариант лучше

2021-05-17 10:37 UTC, Grads521 commented on src/components/main.vue
> +                isPhoneVisible: true,
Вообще, я думаю засунуть в метод функцию, которая меняет надпись в зависимости от состояния телефора. Когда true будет скрыть и наоборот. Но как это сделать я хз

2021-05-17 10:39 UTC, ninedev-i commented on src/components/main.vue
> +                isPhoneVisible: true,
Это можно не пихать в функцию, а сделать прямо на вёрстке через тернарный оператор

2021-05-17 11:34 UTC, ninedev-i requested changes

2021-05-17 11:34 UTC, ninedev-i commented on src/components/main.vue
> +                <p>{{ isPhoneVisible ? 'Скрыть телефон' : ' Показать телефон' }}</p>
Ты тут не перепутал местами?

2021-05-17 11:44 UTC, ninedev-i requested changes
#

2021-05-17 12:02 UTC, Grads521 commented
Можно закрывать пул реквест и в main переводить?

2021-05-17 12:02 UTC, Grads521 commented
Твоего сообщения последнего невидно.

2021-05-17 12:39 UTC, ninedev-i approved these changes

2021-05-17 12:39 UTC, merged